name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a suitable Python version

    - name: Install uv
      run: |
        pip install uv

    - name: Install dependencies
      run: |
        uv sync --with dev

    - name: Run Pylint and save score
      run: |
        pylint dit_ml tests > pylint_output.txt || true # Allow failure so workflow continues

    - name: Run tests with pytest
      id: run_tests # Add this ID to reference the step outcome
      run: |
        pytest --junitxml=report.xml --cov=dit_ml tests/

    - name: Generate Badges
      uses: action-badges/core@0.3.0
      with:
        slug: ${{ github.repository }}
        badges: |
          - name: Pylint Score
            path: pylint_output.txt
            label: Pylint
            color: green
            icon: python
            parser: regex
            pattern: 'Your code has been rated at ([\d.]+)/10'
            value: '$1'
          - name: Tests
            label: Tests
            icon: check
            named-status: |
              success: passing
              failure: failing
            status: ${{ steps.run_tests.outcome }} # Reference the outcome of the pytest step
