name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Pylint
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: uv sync --extra dev

    - name: Install project in editable mode
      run: uv pip install -e .

    - name: Run Pylint and save score
      run: |
        uv run pylint dit_ml tests > pylint_output.txt || true # Allow failure so workflow continues

    - name: Extract Pylint Score
      id: extract_pylint_score
      run: |
        SCORE=$(grep -oP 'Your code has been rated at \K[\d.]+(?=/10)' pylint_output.txt || echo "N/A")
        echo "SCORE=$SCORE" >> $GITHUB_OUTPUT
        echo "Pylint score: $SCORE"

    - name: Generate Pylint Badge
      uses: action-badges/core@0.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file-name: pylint_badge.svg
        label: Pylint
        message: ${{ steps.extract_pylint_score.outputs.SCORE }}/10
        message-color: green

    - name: Upload Pylint badge
      uses: actions/upload-artifact@v4
      with:
        name: pylint-badge
        path: pylint_badge.svg

  test:
    runs-on: ubuntu-latest
    name: Pytest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: uv sync --extra dev

    - name: Install project in editable mode
      run: uv pip install -e .

    - name: Run tests with pytest
      id: run_tests
      run: |
        uv run pytest --junitxml=report.xml --cov=dit_ml tests/
        echo "Test outcome: ${{ job.status }}"

    - name: Generate Tests Badge
      uses: action-badges/core@0.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file-name: tests_badge.svg
        label: Tests
        message: ${{ job.status }} # Use job status for overall test outcome
        message-color: ${{ job.status == 'success' && 'green' || 'red' }}

    - name: Upload Tests badge
      uses: actions/upload-artifact@v4
      with:
        name: tests-badge
        path: tests_badge.svg

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.xml
