name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a suitable Python version

    - name: Install uv
      run: |
        pip install uv

    - name: Install dependencies
      run: |
        uv sync

    - name: Run Pylint
      run: |
        # Install pylint if not in uv.lock
        uv pip install pylint
        pylint dit_ml tests

    - name: Run tests with pytest
      run: |
        pytest tests/
