name: Publish Python 🐍 distributions to PyPI

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/dit-ml
    permissions:
      id-token: write # Required for trusted publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: pip install uv

      - name: Build package
        run: uv build

      - name: Publish package to PyPI
        run: uv publish
